alias lnc='lein compile'
alias lnd='lein deps'
alias lnr='lein repl'
alias lnt='lein test'
alias lne='lein expectations'
alias lnrs='lein ring server'
alias lni='lein install'
alias lnu='lein uberjar'
